---
title: "Data Wrangling"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")
```

```{r}
## read gapminder csv. Note the readr:: prefix identifies which package it's in
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')

# inspect the data
gapminder # looks at all the data
head(gapminder) #gives the first 6 by default
tail(gapminder) # gives the last 6 by default
head(gapminder, 3) # will give you first 3 can do same with tail

#summary statistics

str(gapminder)
summary(gapminder)

install.packages("skimr")
skimr::skim(gapminder)

names(gapminder) # column names
dim(gapminder) #dimensions
ncol(gapminder) # number of columns
nrow(gapminder) # number of rows

# reverse-engineer data
c(nrow(gapminder), ncol(gapminder))

```

# start of dplyr!
```{r}
# filter by rows
filter(gapminder, lifeExp < 29)
filter(gapminder, country == "Mexico")
filter(gapminder, country %in% c("Mexico", "Peru", "Brazil"))
filter(gapminder, country == "Mexico", year == 2002)

# find mean lifeExp of Sweden
sweden <- filter(gapminder, country == "Sweden")
mean(sweden$lifeExp)
mean(sweden) # error: argument is not numeric or logical: returning NA[1] NA
```

```{r}
# select by columns
select(gapminder, year, lifeExp)
select(gapminder, -continent, -lifeExp) # - will exclude these columns

# use select and filter together
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)
```

# The pipe operator will change your life!

```{r}
# this:
gapminder %>% head(3)
# is equivalent to:
head(gapminder, 3)

# let's improve this with pipes!
gap_cambodia <- filter(gapminder, country == "Cambodia")
gap_cambodia2 <- select(gap_cambodia, -continent, -lifeExp)

gap_cambodia <- gapminder %>% 
  filter(country == "Cambodia") %>% 
  select(-continent, -lifeExp)
```
# the above is creating different variables if you go into console and type gap_cambodia and hit return then you will get the data to show.

```{r}
# mutate adds new variables
gapminder %>% 
  mutate(index = 1:nrow(gapminder))

gapminder %>% 
  mutate(planet = "Earth")

gapminder %>% 
  mutate(gdp = pop * gdpPercap)

#Challenge:
#Find the maximum gdpPerCap of Egypt and Vietnam. Create a new column. Only one max between the two countries.

gapminder %>%
  filter(country %in% c("Egypt", "Vietnam")) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  mutate(max_gdp = max(gdp))



```

# 'group_by()' groups!

```{r}
#with mutate()
gap_grouped <-gapminder %>% 
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap,
         max_gdp = max(gdp)) %>% 
  ungroup()

# with summarize() or summarise()
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup()
```

# 'arrange()' arranges columns
```{r}
gap_summarized <- gapminder %>% 
  group_by(country) %>% 
  mutate(gdp = pop * gdpPercap) %>% 
  summarize(max_gdp = max(gdp)) %>% 
  ungroup() %>% 
  arrange(max_gdp) #default is lowest to highest
  #arrange(desc(max_gdp)) #using this arrange instead puts it highest to lowest
```

# Joining data

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

# explore

co2 %>% head()
co2 %>% dim()

# create a new gapminder variable with only 2007 data

gap_2007 <- gapminder %>% 
  filter(year == 2007)

gap_2007 %>% dim() # 142 observations

# left_join gap_2007 to co2
lj <- left_join(gap_2007, co2, by = "country")
# another way to write this;
lj <- gap_2007 %>% 
  left_join(co2, by = "country")


# right_join gap_2007 to co2
rj <- right_join(gap_2007, co2)
# this is the same as
lj2 <- left_join(co2, gap_2007, by = "country")

```


