---
title: "Graphics with ggplot2"
author: "Tina"
date: "10/22/2018"
output: html_document
---

## Load packages

```{r}
#install.packages("tidyverse")
## once you install something you don't have to do it again which is why I added the # in front of install.packages to actually run things do a command enter or hit green right point arrow to run.
## tidyverse is a "package of packages" and contains many of the packages we will use in the workshop, including ggplot2

#load installed packages using `library()`
library(tidyverse)
```

## Load NP data

```{r load_data}
#National Parks in California
ca <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/ca.csv") 

#Acadia National Park
acadia <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/acadia.csv")

#Southeast US National Parks
se <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/se.csv")

#2016 Visitation for all Pacific West National Parks
visit_16 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/visit_16.csv")

#All Nationally designated sites in Massachusetts
mass <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/mass.csv")
```

Start with the California ('ca') dataset

```{r}
head(ca)
View(ca) #views the data in spreadsheet form
```

Plot visitation to all CA National Parks over time

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors))
```

```{r}
ggplot(data = ca) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  labs(x = "Year",
       y = "Visitation",
       title = "California National Park Visitation") +
theme_bw() + #this utilized the "black and white"" theme
theme(legend.title = element_blank()) #this removed the legend title
```
```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) + #color is by park name
  labs(x = "Year",
       y = "Visitation",
       title = "Southeast States National Park Visitation") +
theme_bw() + #this utilized the "black and white"" theme
theme(legend.title = element_blank())#this removed the legend title
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14)
```


```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = state)) + #color is now by State
  labs(x = "Year",
       y = "Visitation Numbers",
       title = "Southeast States National Park Visitation") +
theme_bw() + #this utilized the "black and white"" theme
theme(legend.title = element_blank(), #this removed the legend title
    axis.text.x = element_text(angle = 45, hjust = 1, size = 14)) #this angles the x axis years and increases their size.
```

# Faceting Plots

```{r}
ggplot(data = se) +
  geom_point(aes(x = year, y = visitors, color = park_name)) +
  facet_wrap(~ state, scales = "free") +
theme(axis.text.x = element_text(angle = 90))
```

# geoms

```{r}
ggplot(data = se) +
  geom_jitter(aes(x = park_name, y = visitors), alpha = 0.4, width = 0.1, color = "blue") +
  coord_flip() #if color was inside aes then it would be looking for a color, coor outside assigns data a color
```
#

```{r}
ggplot(se) +
  geom_line(aes(x = year, y = visitors, color = park_name)) +
  theme_bw()
```

# Multiple geoms on one plot

```{r}
ggplot(data = acadia) +
  geom_point(aes(x = year, y = visitors)) +
  geom_line(aes(x = year, y = visitors)) +
  geom_smooth(aes(x = year, y = visitors))
```

```{r}
#install.packages("ggthemes")
library(ggthemes)
ggplot(data = acadia, aes(x = year, y = visitors)) +
  geom_point() +
  geom_line() +
  geom_smooth() +
  theme_economist()
# this plot is the same as the above except the asthetics are captured with the data instead of repeating them line by line.
```

# Bar Charts

```{r}
ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")
```

# Save a ggplot

```{r}
myplot <- ggplot(data = visit_16, aes(x = state, y = visitors, fill = park_name)) +
  geom_bar(stat = "identity", position = "dodge")

myplot

ggsave(filename = "myplot.png", myplot, dpi = 300)
```


